source.. = src/main/java
output.. = bin/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               about.html,\
               lib/js-language.jar,\
               lib/truffle-runtime.jar,\
               lib/truffle-enterprise.jar,\
               lib/polyglot.jar,\
               lib/launcher-common.jar,\
               lib/jline.jar,\
               lib/collections.jar,\
               lib/nativeimage.jar,\
               lib/word.jar,\
               lib/truffle-api.jar,\
               lib/icu4j.jar,\
               lib/groovy-jsr223.jar
               